function(embed_res ns line_limit target_dir target_file shaders)
    find_program(DOTNET_PROG dotnet)
    if(DOTNET_PROG)
        message("Found .NET Program at \"${DOTNET_PROG}\"")
        set(EMBED_RES_SCRIPT "${CMAKE_SOURCE_DIR}/../../../csx/embed_res.csx")
        if(EXISTS ${EMBED_RES_SCRIPT})
            message("CS/Invoke : Embed Res (${ns} ${line_limit} ${target_dir} ${target_file} ${shaders})")
            execute_process(COMMAND ${DOTNET_PROG} script ${EMBED_RES_SCRIPT} -- ${ns} ${line_limit} ${target_dir} ${target_file} "${shaders}" "CPP;HPP" WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
        else()
            message("CS/Invoke : Cannot find Resource Embedder script that should be located at ${EMBED_RES_SCRIPT}")
        endif()
    else()
        message("Cannot find .NET Toolset, Embedded Resource creation is aborted. but do not worry, it will only needed if you've modified the C++ project resources e.g Shaders")
    endif()
endfunction()